apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  labels:
    argocd-application: true
spec:
  project: default
  source:
    repoURL: https://github.com/44smkn/argocd-sample
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
