apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sample-applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/44smkn/argocd-sample
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated: {}
