apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.6
  - ../../base
  - repo-secrets.yaml
  - ingress-certificate.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - ingress-domain.yaml
  - argocd-server-cmd.yaml

namespace: argocd
