apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  lebals:
    argocd-application: true
spec:
  project: default
  source:
    repoURL: https://github.com/44smkn/argocd-sample
    targetRevision: HEAD
    path: apps/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
