apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  source:
    helm:
      parameters:
        - name: sources
          value: "{ingress}"
        - name: provider
          value: google
        - name: policy
          value: upsert-only
        - name: registry
          value: txt
        - name: txtOwnerId
          value: 44smkn
        - name: domainFilters
          value: "{argocdsample-a1cac346.com}"
        - name: "serviceAccount.annotations.iam\\.gke\\.io/gcp-service-account"
          value: external-dns@infra-forklift-278011.iam.gserviceaccount.com
